spring:
  application:
    name: RabbitMQ-Topic

  rabbitmq:
    host: rabbitmq      # 192.168.0.100 rabbitmq
    port: 5672          # Porta AMQP correta
    username: admin     # usuário definido no docker-compose
    password: admin123  # senha definida no docker-compose
    virtual-host: /

server:
  port: ${SERVER_PORT:8082}


# ===============================
# = ACTUATOR
# ===============================
management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true

# ===============================
# = OPENZIPKIN
# ===============================
  tracing:
    sampling:
      probability: 0.2   # 20% das requisições; em produção use valores menores
    export:
      zipkin:
        endpoint: http://zipkin:9411/api/v2/spans
