spring:
  application:
    name: RabbitMQ-Topic

  rabbitmq:
    host: 192.168.0.100      # 192.168.0.100
    port: 5672          # Porta AMQP correta
    username: admin     # usuário definido no docker-compose
    password: admin123  # senha definida no docker-compose
    virtual-host: /

server:
  port: ${SERVER_PORT:8282}


# ===============================
# = ACTUATOR
# ===============================
management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
